### ISSUE TITLE
[Bug] Offline training broken

### ISSUE THREAD

**Issue by stoical07** [sgl-project/SpecForge#133]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/SpecForge/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

Offline training has been broken by #97.

Running the example script from `README.md` shows the following error: 
`'OfflineEagle3Model' object has no attribute 'attention_backend'`

cc @yubofredwang @FrankLeeeee @zyksir

### Reproduction

```bash ./examples/run_llama3_eagle3_offline.sh```

### Environment

```Python: 3.10.14 (main, Jul 14 2024, 22:24:12) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA H100 80GB HBM3
GPU 0,1 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.6, V12.6.77
CUDA Driver Version: 550.163.01
PyTorch: 2.7.1+cu126
sglang: 0.4.9.post2
sgl_kernel: 0.2.5
flashinfer_python: 0.2.7.post1
triton: 3.3.1
transformers: 4.53.0
torchao: 0.9.0
numpy: 2.2.6
aiohttp: 3.12.13
fastapi: 0.116.0
hf_transfer: 0.1.9
huggingface_hub: 0.33.2
interegular: 0.3.3
modelscope: 1.27.1
orjson: 3.10.18
outlines: 0.1.11
packaging: 25.0
psutil: 7.0.0
pydantic: 2.11.7
python-multipart: 0.0.20
pyzmq: 27.0.0
uvicorn: 0.35.0
uvloop: 0.21.0
vllm: Module Not Found
xgrammar: 0.1.21
openai: 1.93.1
tiktoken: 0.9.0
anthropic: 0.57.1
litellm: 1.74.0.post1
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    SYS     SYS     SYS     SYS     NODE    NODE    64-127,192-255  1               N/A
GPU1    NV18     X      SYS     SYS     SYS     SYS     NODE    NODE    64-127,192-255  1               N/A
NIC0    SYS     SYS      X      NODE    NODE    NODE    SYS     SYS
NIC1    SYS     SYS     NODE     X      PIX     NODE    SYS     SYS
NIC2    SYS     SYS     NODE    PIX      X      NODE    SYS     SYS
NIC3    SYS     SYS     NODE    NODE    NODE     X      SYS     SYS
NIC4    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE
NIC5    NODE    NODE    SYS     SYS     SYS     SYS     NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5


ulimit soft: 10000000```

**Comment by yubofredwang** [comment]
Fixing now

**Comment by ghost** [comment]
Thanks for the amazing work @yubofredwang! Look forward to flex attention for offline too :smile:

**Comment by yubofredwang** [comment]
@stoical07 code is merged, please check again. Thanks!

**Comment by yubofredwang** [comment]
Closing for now. Feel free to reopen if issue persists.
